ext_render_snorm-render: Fix deprecated-non-prototype warning
tests/spec/ext_render_snorm/render.c:177:53: warning: too many arguments in call to 'create_and_bind_empty_texture'
  177 |         GLuint fbo_tex = create_and_bind_empty_texture(test);
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     ^
tests/spec/ext_render_snorm/render.c:177:48: warning: passing arguments to 'create_and_bind_empty_texture' without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
  177 |         GLuint fbo_tex = create_and_bind_empty_texture(test);
      |                                                       ^

Fixes: 5712e5965 ("ext_render_snorm-render: test for GL_EXT_render_snorm")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Tapani Pälli <tapani.palli@intel.com>
Part-of: <https://gitlab.freedesktop.org/mesa/piglit/-/merge_requests/856>