tests/ext_direct_state_access: fix pointer types
Fixes build failures on mingw32 that look like:
```
build/mingw32/tests/util/piglit-dispatch-gen.h:6685:31: error: initialization of 'void (*)(GLenum,  GLuint,  GLfloat *)' {aka 'void (*)(unsigned int,  unsigned int,  float *)'} from incompatible pointer type 'PFNGLGETFLOATINDEXEDVEXTPROC' {aka 'void (__attribute__((stdcall)) *)(unsigned int,  unsigned int,  float *)'} [-Wincompatible-pointer-types]
 6685 | #define glGetFloatIndexedvEXT piglit_dispatch_glGetFloatIndexedvEXT
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests/spec/ext_direct_state_access/indexed-state-queries.c:330:17: note: in expansion of macro 'glGetFloatIndexedvEXT'
  330 |                 glGetFloatIndexedvEXT, "GetFloatIndexedvEXT", 12
      |                 ^~~~~~~~~~~~~~~~~~~~~
build/mingw32/tests/util/piglit-dispatch-gen.h:6685:31: note: (near initialization for 'get_float_12.get_float_fn')
 6685 | #define glGetFloatIndexedvEXT piglit_dispatch_glGetFloatIndexedvEXT
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests/spec/ext_direct_state_access/indexed-state-queries.c:330:17: note: in expansion of macro 'glGetFloatIndexedvEXT'
  330 |                 glGetFloatIndexedvEXT, "GetFloatIndexedvEXT", 12
      |                 ^~~~~~~~~~~~~~~~~~~~~
```
(Repeated twice for each of the 3 pointers)

Fixes: 3cd7ce2b44e3a093912b ("ext_direct_state_access: glGet*IndexedvEXT")
Part-of: <https://gitlab.freedesktop.org/mesa/piglit/-/merge_requests/1072>